# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788f149789099f2bf871140bb366304126c04618c94a9e3f79ea4be06544b7f83a9ad02428a891075d60af2a083dfb19ca23c2f06217ce3fdd71ff3aafed1d84

test:
  secret_key_base: 944664216723ac9f51c1cca82604e524d4ebd4c5bd8bb1c59560940c899018e52116d87435a34b7e0a24bc873f620e9ef760cc118aab864eda6c495ecca4b28e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 7531e602e3514df89dabc0443e5deb487695d1dc3955077e6969c5de93e74654382ff239319833de2be16b0c5b8fe0fcf2d4d3a44eb1127905dfe69ea1910aa6
